image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build and Launch
    init: |
      atlas-package
      atlas-run --http-port 1000000
    command: |
      atlas-run
  - name: Launch
    command: |
      gp ports await 1990
      gp preview --external "$(gp url 1990)/confluence"

ports:
  - port: 1990
    visibility: private
    onOpen: ignore
  - port: 8091
    visibility: private
    onOpen: ignore
  - port: 9092
    visibility: private
    onOpen: ignore
  - port: 35061
    visibility: private
    onOpen: ignore